# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 16:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('type', models.CharField(max_length=500)),
                ('voltage', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('powerbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='power.PowerBaseModel')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            bases=('power.powerbasemodel',),
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('powerbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='power.PowerBaseModel')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('power.powerbasemodel',),
        ),
    ]
