# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_auto_20160821_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='powerbasemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='station',
            name='powerbasemodel_ptr',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='PowerBaseModel',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
