# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 17:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power', '0003_auto_20160821_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('voltage', models.CharField(blank=True, max_length=500, null=True)),
                ('line_string', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('voltage', models.CharField(blank=True, max_length=500, null=True)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
