# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0005_auto_20160821_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='type',
            new_name='power_type',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='type',
            new_name='power_type',
        ),
    ]
