# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 17:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0006_auto_20160821_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_string',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
